name: Deploy to VPS via FTP

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: npm install

            - name: Build application
              run: npm run build

            - name: Deploy to VPS via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 21
                  local-dir: build
                  remote-dir: /
                  protocol: ftp
